### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by mbazaliy** [rodionovd/SWRoute#1]
Nice work! Any plans to add iOS support ?

**Comment by rodionovd** [comment]
@mbazaliy thanks! 
Well, actually `rd_route()` does't work on not-jailbroken iOS, but you still can use any other library like [`libevil`](https://github.com/landonf/libevil_patch) by Landon Fuller:  

``` haskell
@asmname("evil_init")
    func evil_init();
@asmname("evil_override_ptr")
    func evil_override_ptr(UInt64, UInt64, CMutablePointer<UInt64>) -> CInt;

evil_init()
evil_override_ptr(rd_get_func_impl(DemoClass().demoMethod),
                  rd_get_func_impl(someFunction),
                  nil)
```

**Comment by rodionovd** [comment]
I've left this note on iOS support in README file, so anyone can find it.  

https://github.com/rodionovd/SWRoute#swroute-and-ios

**Comment by mbazaliy** [comment]
Thnx, I will try. The bad thing is that libevil seems not work with arm64.
